name: 'New Repository Checklist'
description: 'List of steps to follow when creating a new repository.'
labels: ['project-management', 'enhancement']
body:
  - type: markdown
    attributes:
      value: 'Write a summary of the purpose of the new repository.'
  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Repository Purpose'
