name: 'New Repository Checklist'
description: 'List of steps to follow when creating a new repository.'
labels: ['project-management', 'enhancement']
body:
  - type: markdown
    attributes:
      value: 'Write a summary of the purpose of the new repository.'
  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Repository Purpose'
  - type: checkboxes
    attributes:
      label: 'Project'
      description: 'Please assign this issue to a project.'
      options:
        - label: 'I have assigned this issue to a project.'
          required: true
  - type: checkboxes
    attributes:
      label: 'Checklist'
      description: 'Steps to do when creating a new repository before it is ready for work.'
      options:
        - label: 'I used the `github-template` template repository, and copied all branches.'
        - label: 'I unchecked `General` => `Preserve this repository`.'
