name: 'New Metadata Repository Checklist'
description: 'List of steps to follow when creating a new metadata repository.'
labels: ['project-management', 'enhancement']
body:
  - type: markdown
    attributes:
      value: 'Write a summary of the purpose of the new repository.'
  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Repository Purpose'
  - type: checkboxes
    attributes:
      label: 'Project'
      description: 'Please assign this issue to a project.'
      options:
        - label: 'I have assigned this issue to a project.'
          required: true
  - type: checkboxes
    attributes:
      label: 'Steps to follow when creating a new repository before it is ready for work.'
      options:
        - label: 'I used the `github-template` template repository, and only copied the `development` (default) branch.'
        - label: 'I unchecked `General` => `Preserve this repository`.'
        - label: 'I checked `General` => `Allow squash merging` => `default to pull request title`.'
        - label: 'I unchecked `General` => `Allow rebase merging`.'
        - label: 'I checked `General` => `Always suggest updating pull request branches`.'
        - label: 'I checked `General` => `Allow auto-merge`.'
        - label: 'I checked `General` => `Automatically delete head branches`.'
        - label: 'I set `General` => `Limit how many branches and tags can be updated in a single push` to 2.'
        - label: 'I created the development team `development-repository-name` with the parent team `development`.'
        - label: 'I assigned the aforementioned team to this repository.'
        - label: 'I checked `Actions` => `General` => `Disable Actions`.'
        - label: 'I created the following branch/tag rulesets.'
  - type: checkboxes
    attributes:
      label: 'Branch Ruleset `Disabled Branch Names`'
      options:
        - label: 'Exclude target `development`.'
        - label: 'Exclude target `issue-[0-9]-**`.'
        - label: 'Exclude target `issue-[0-9][0-9]-**`.'
        - label: 'Exclude target `issue-[0-9][0-9][0-9]-**`.'
        - label: 'Exclude target `issue-[0-9][0-9][0-9][0-9]-**`.'
        - label: 'Exclude target `issue-[0-9][0-9][0-9][0-9][0-9]-**`.'
        - label: 'Include target option `All branches`.'
        - label: 'Checkmark `Restrict creations`.'
        - label: 'Checkmark `Block force pushes`.'
  - type: checkboxes
    attributes:
      label: 'Branch Ruleset `Environment Branches`'
      options:
        - label: 'Include target `development`.'
        - label: 'Checkmark `Restrict deletions`.'
        - label: 'Checkmark `Require linear history`.'
        - label: 'Checkmark `Require signed commits`.'
        - label: 'Checkmark `Require a pull request before merging`.'
        - label: 'Checkmark `Require approval of the most reviewable push`.'
        - label: 'Checkmark `Require conversation resolution before merging`.'
        - label: 'Checkmark `Block force pushes`.'
  - type: checkboxes
    attributes:
      label: 'Branch Ruleset `Feature Branches`'
      options:
        - label: 'Include target `issue-[0-9]-**`.'
        - label: 'Include target `issue-[0-9][0-9]-**`.'
        - label: 'Include target `issue-[0-9][0-9][0-9]-**`.'
        - label: 'Include target `issue-[0-9][0-9][0-9][0-9]-**`.'
        - label: 'Include target `issue-[0-9][0-9][0-9][0-9][0-9]-**`.'
        - label: 'Checkmark `Require signed commits`.'
        - label: 'Checkmark `Require linear history`.'
        - label: 'Checkmark `Block force pushes`.'
  - type: checkboxes
    attributes:
      label: 'Tag Ruleset `Disabled Tag Names`'
      options:
        - label: 'Include target option `All branches`.'
        - label: 'Checkmark `Restrict creations`.'
        - label: 'Checkmark `Block force pushes`.'
